---
#
# Packages
# k8s_core_packages  : required for every node
# k8s_addon_packages : optional node-level packages
# k8s_controller_packages: admin tools installed on controllers
#
k8s_core_packages:
  - containerd
  - kubeadm
  - kubelet

k8s_addon_packages:
  - open-iscsi   # For longhorn

k8s_controller_packages:
  - kubectl
  - helm
  - k9s
  - git
  - nano
  - less
