# Generated by Terraform. Not recommended to edit manually.

all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: arch
  children:
    controllers:
      hosts:
%{ for i, c in controllers ~}
        ${c.name}:
          ansible_host: 192.168.0.${221 + i}
%{ endfor ~}
    workers:
      hosts:
%{ for i, w in workers ~}
        ${w.name}:
          ansible_host: 192.168.0.${231 + i}
%{ endfor ~}
